### ISSUE TITLE
Model overwrite is ignored for category image uploads

### ISSUE THREAD

**Issue by Ithalan** [CopeX/PNGUploadFix#2]
I'm working on a shop that has the same issue of transparency being discarded on PNG uploads, and was hoping to solve it with this module. It worked for fine for allowing PNG image uploads to products to retain their transparency, but it fails for uploads to the category image.

I managed to track the issue down to being caused by the category upload still using the standard Mage_Core_Model_File_Validator_Image model, despite the module being installed as-is and active, and the product upload having been confirmed as using the module's model overwrite. I've been unable to determine why Magento is doing this however

The shop I'm attempting to fix with the module is running version 1.9.1.1

I've also tested on a completely fresh install of 1.9.3.6 and found that the problem of the overwrite being ignored for category image uploads is present there as well.

**Comment by pointia** [comment]
This module does only cover product image uploads for magento prior 1.9.3.4. Since 1.9.3.4 transparent images are processed the way this extension provides.

If Magento does ignore the rewrite you could try to download Mage_Core_Model_File_Validator_Image from 1.9.3.4 and put it in the local code pool. Hope that helps.
